export const liveTokenSet = [
  {
    name: "Ether",
    symbol: "ETH",
    balance: 0,
    icon: "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
  },
  {
    name: "Bitcoin",
    symbol: "BTC",
    balance: 0,
    icon: "https://raw.githubusercontent.com/ubeswap/default-token-list/master/assets/asset_WBTC.png",
  },
  {
    name: "BNB",
    symbol: "BNB",
    balance: 0,
    icon: "https://raw.githubusercontent.com/Uniswap/assets/master/blockchains/smartchain/assets/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c/logo.png",
  },
  {
    name: "Solana",
    symbol: "SOL",
    balance: 0,
    icon: "https://assets.coingecko.com/coins/images/22876/thumb/SOL_wh_small.png?1644224316",
  },
  // {
  //   name: "Tether USD",
  //   symbol: "USDT",
  //   balance: 0,
  //   icon: "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png",
  // },
  {
    name: "Polkadot",
    symbol: "DOT",
    balance: 0,
    icon: "https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@latest/128/color/dot.png",
  },
  {
    name: "Chainlink",
    symbol: "LINK",
    balance: 0,
    icon: "https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@latest/128/color/link.png",
  },
  {
    name: "Avalanche",
    symbol: "AVAX",
    balance: 0,
    icon: "https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@latest/128/color/avax.png",
  },
  {
    name: "TRON",
    symbol: "TRX",
    balance: 0,
    icon: "https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@latest/128/color/trx.png",
  },
  // {
  //   name: "Polygon",
  //   symbol: "MATIC",
  //   balance: 0,
  //   icon: "https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@latest/128/color/matic.png",
  // },
  {
    name: "Uniswap",
    symbol: "UNI",
    balance: 0,
    icon: "https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@latest/128/color/uni.png",
  },
  {
    name: "Cosmos",
    symbol: "ATOM",
    balance: 0,
    icon: "https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@latest/128/color/atom.png",
  },
  // {
  //   name: "Dai Stablecoin",
  //   symbol: "DAI",
  //   balance: 10000,
  //   icon: "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png",
  // },
  {
    name: "Cardano",
    symbol: "ADA",
    balance: 0,
    icon: "https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@latest/128/color/ada.png",
  },
  {
    name: "XRP",
    symbol: "XRP",
    balance: 0,
    icon: "https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@latest/128/color/xrp.png",
  },
];
