version: "3.8"

services:
  order-service:
    image: rssutardev/paperdex:order-service-dev-latest
    container_name: order-service
    restart: always
    ports:
      - 4002:4002
    networks:
      - paperdex_network
    environment:
      NODE_ENV: ${NODE_ENV}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      DIRECT_URL: ${DIRECT_URL}
      DATABASE_URL: ${DATABASE_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      RESEND_API_KEY: ${RESEND_API_KEY}
      EMAIL_FROM: ${EMAIL_FROM}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      NEXT_PUBLIC_CLIENT_SERVICE: ${NEXT_PUBLIC_CLIENT_SERVICE}
      NEXT_PUBLIC_USER_SERVICE: ${NEXT_PUBLIC_USER_SERVICE}
      NEXT_PUBLIC_ORDER_SERVICE: ${NEXT_PUBLIC_ORDER_SERVICE}
      NEXT_PUBLIC_AUTH_SERVICE: ${NEXT_PUBLIC_AUTH_SERVICE}
      REDIS_URL: ${REDIS_URL}

  user-service:
    image: rssutardev/paperdex:order-service-dev-latest
    container_name: user-service
    restart: always
    ports:
      - 4001:4001
    networks:
      - paperdex_network
    environment:
      NODE_ENV: ${NODE_ENV}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      DIRECT_URL: ${DIRECT_URL}
      DATABASE_URL: ${DATABASE_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      RESEND_API_KEY: ${RESEND_API_KEY}
      EMAIL_FROM: ${EMAIL_FROM}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      NEXT_PUBLIC_CLIENT_SERVICE: ${NEXT_PUBLIC_CLIENT_SERVICE}
      NEXT_PUBLIC_USER_SERVICE: ${NEXT_PUBLIC_USER_SERVICE}
      NEXT_PUBLIC_ORDER_SERVICE: ${NEXT_PUBLIC_ORDER_SERVICE}
      NEXT_PUBLIC_AUTH_SERVICE: ${NEXT_PUBLIC_AUTH_SERVICE}
      REDIS_URL: ${REDIS_URL}

networks:
  paperdex_network:
    driver: bridge
