name: Build and Push Order Service to Docker Hub

on:
  push:
    branches: ["main", "dev"]
    paths:
      - "packages/order-service/**"
      - "packages/order-service/Dockerfile"

env:
  DOCKER_HUB_REPO: rssutardev/paperdex

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using secrets for security
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Set image tag based on the current branch
      - name: Set image tag based on branch
        id: set-tag
        run: |
          TAG="order-service-${GITHUB_REF_NAME}-latest"
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      # Step 5: Build and push Docker image with NO cache
      - name: Build and push Docker image (no cache)
        uses: docker/build-push-action@v5
        with:
          context: . # Root of monorepo
          file: packages/order-service/Dockerfile
          push: true
          no-cache: true # 🔥 Build fresh every time
          tags: ${{ env.DOCKER_HUB_REPO }}:${{ steps.set-tag.outputs.TAG }}

      # Step 6: Verify the image was built correctly
      - name: Verify image
        run: |
          docker pull ${{ env.DOCKER_HUB_REPO }}:${{ steps.set-tag.outputs.TAG }}
          docker run --rm ${{ env.DOCKER_HUB_REPO }}:${{ steps.set-tag.outputs.TAG }} node --version
