# name: Build Order Service Docker Image

# on:
#   push:
#     branches: ["feat/github-actions"] # Changed to your branch
#     paths:
#       - "packages/order-service/**"
#       - "packages/order-service/Dockerfile"

# jobs:
#   build-order-service:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Build Docker image
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           file: packages/order-service/Dockerfile
#           tags: paperdex/order-service:local-build
#           load: true
#           cache-from: type=gha
#           cache-to: type=gha,mode=max

#       - name: Verify image
#         run: |
#           docker image inspect paperdex/order-service:local-build
#           docker run --rm paperdex/order-service:local-build node --version

name: Build and Push Order Service to Docker Hub

on:
  push:
    branches: ["feat/github-actions"]
    paths:
      - "packages/order-service/**"
      - "packages/order-service/Dockerfile"

env:
  DOCKER_HUB_REPO: rssutardev/paperdex # Your Docker Hub repository name
  DOCKER_HUB_TAG: order-service-latest # Tag for the image

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: packages/order-service/Dockerfile
          push: true
          tags: ${{ env.DOCKER_HUB_REPO }}:${{ env.DOCKER_HUB_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify image
        run: |
          docker pull ${{ env.DOCKER_HUB_REPO }}:${{ env.DOCKER_HUB_TAG }}
          docker run --rm ${{ env.DOCKER_HUB_REPO }}:${{ env.DOCKER_HUB_TAG }} node --version
